version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/cypress-react-selector
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm test
