version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build-and-test:
    executor:
      name: cypress/base-12-6-0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx cypress cache clear
            - run: npx cypress run --headless
workflows:
  build-and-test:
    jobs:
      - build-and-test
