version: 2.1
orbs:
  cypress: cypress-io/cypress@1

executors:
  node-executor:
    docker:
      - image: cimg/node:14.16.0 

jobs:
  test-cypress-react-selector:
    executor: node-executor
    steps: 
      - checkout
      - run :
          name: install packages
          command: npm i
      - run:
          name: integration test
          command: npx cypress run
      - run:
          name: component test
          command: npx cypress test-ct

workflows:
  build:
    jobs:
      - test-cypress-react-selector
