version: 2.1

jobs:
  build-and-test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:12.16.1
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx cypress cache clear
            - run: npx cypress run --headless
workflows:
  build-and-test:
    jobs:
      - build-and-test
